### ISSUE TITLE
Embedded app not loading inside Shopify admin using <EmbeddedApp> component

### ISSUE THREAD

**Issue by buggy** [Shopify/polaris-react-archive#28]
# Issue summary

Previously I've been initializing my embedded app using

```javascript
ShopifyApp.init({
  apiKey: 'YOUR_APP_API_KEY',
  shopOrigin: 'https://CURRENT_LOGGED_IN_SHOP.myshopify.com'
});
```

as described on https://help.shopify.com/api/sdks/shopify-apps/embedded-app-sdk/initialization

If the page is opened outside of the Shopify admin then this causes the Shopify admin to load showing my page inside it.

From the documentation I believe that when I'm using Polaris I don't need to call `ShopifyApp.init()` as `<EmbeddedApp></EmbeddedApp>` is supposed to handle this for me. For example:

```javascript
<EmbeddedApp shopOrigin={shopOrigin} apiKey={apiKey} >
    <ResourcePicker
      open
      products
      onSelection={(resources) => console.log('Selected resources ', resources)}
    />
</EmbeddedApp>
```

This appears to be attempting to initialize Shopify by posting a message:

```
"Posting message: {"message":"Shopify.API.initialize","data":{"apiKey":"xxxxxxxxxxxxx","shopOrigin":"https://growing-ecommerce.myshopify.com","metadata":{"@shopify/polaris":"1.0.2"}}} to https://growing-ecommerce.myshopify.com }"
```

That fails if the page isn't already loaded inside the Shopify Admin with

```
Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://growing-ecommerce.myshopify.com’) does not match the recipient window’s origin (‘https://localhost:5000’).
```

## Expected behavior

If I open a page with `<EmbeddedApp></EmbeddedApp>` on it outside of the Shopify Admin then I expect it to load the Shopify Admin with my page inside it.

This is needed to get back into the Shopify Admin after logging in. For example:

1. User goes to the login page `https://my-app/login?shop=example.myshopify.com`
1. User is redirected to Shopify OAuth page via a full page redirect so they are no longer inside the Shopify Admin (see https://help.shopify.com/api/sdks/shopify-apps/embedded-app-sdk/getting-started)
1. After successful authentication they are redirected back to our app (still outside of the Shopify admin) where they are logged in and redirected to the apps home page
1. The user now sees the app's home page which contains `<EmbeddedApp></EmbeddedApp>` but they remain outside of the Shopify admin because the initialize isn't working. (See "Steps to Reproduce the Problem" for how I'm currently working around this)

## Actual behavior

My page loads without loading the Shopify Admin

## Steps to Reproduce the Problem

1. Create a page with `<EmbeddedApp shopOrigin={shopOrigin} apiKey={apiKey} ></EmbeddedApp>` on it.
1. Visit that page outside of the Shopify Admin.
1. Instead of redirecting you so the page appears as an embedded app inside the Shopify Admin you should see your page outside of the Shopify Admin.
1. Add `ShopifyApp.init({apiKey: apiKey, shopOrigin: shopOrigin });` so that it's called before the `<EmbeddedApp></EmbeddedApp>`
1. Visit the page outside of the Shopify Admin.
1. It should now redirect so the page is loaded as an embedded app inside the Shopify Admin. <-- I'm using this approach to get around it.

## Specifications

- Polaris version: 1.0.2
- React version: 15.5.4
- Browser: Firefox 53.0
- Device: Mac
- Operating System: 10.12.4

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by lemonmade** [comment]
Thanks for the issue, @buggy. This is definitely an omission on our part and we will get it fixed up for the next release.

**Comment by buggy** [comment]
Thanks. Great job with Polaris.

**Comment by lemonmade** [comment]
Should be fixed in 1.0.3.

**Comment by bakura10** [comment]
Hi,

It looks like I still have the issue (sorry, noob to React here). I've tried to install the react-embedded. I've properly been able to add a few components, but whenever I enter the URL, it stays within my browser without redirect to the Shopify admin:

<img width="999" alt="capture d ecran 2017-06-28 a 17 44 28" src="https://user-images.githubusercontent.com/1198915/27646669-7dee4ac6-5c29-11e7-8797-5013287d3730.png">

I have those errors in the console:

<img width="1328" alt="capture d ecran 2017-06-28 a 17 44 55" src="https://user-images.githubusercontent.com/1198915/27646684-895c682a-5c29-11e7-972d-8149c7b0831e.png">

Using last version of Polaris here (1.1). What could be the reason of that?

**Comment by bakura10** [comment]
Oh never mind, I was actually using Polaris 1.0.2 (the examples are using this version instead of the 1.1 part).
